blog/config/routes.rb
Rails.application.routes.draw do
  
  
  resources :resumes do
    resources :skills
  end

  root 'hello#index'
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
end

blog/app/models/resume.rb
class Resume < ApplicationRecord
    has_many :skills, dependent: :destroy
end

blog/app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :resume
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

blog/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: %i[ show edit update destroy ]

  # GET /resumes or /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1 or /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes or /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to resume_url(@resume), notice: "Resume was successfully created." }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1 or /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to resume_url(@resume), notice: "Resume was successfully updated." }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1 or /resumes/1.json
  def destroy
    @resume.destroy

    respond_to do |format|
      format.html { redirect_to resumes_url, notice: "Resume was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resume_params
      params.require(:resume).permit(:Name, :Image_url, :Role, :Location, :Email, :Phone)
    end
end

blog/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/hello_helper.rb
module HelloHelper
end

blog/app/helpers/resumes_helper.rb
module ResumesHelper
end

blog/app/helpers/skills_helper.rb
module SkillsHelper
end

blog/app/views/hello/index.html.erb
<h1>HR Resume Database</h1>
<p><%= link_to 'Resumes', controller: 'resumes' %></p>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/resumes/_form.html.erb
<%= form_for(resume) do |f| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :Name %>
  </div>

  <div class="field">
    <%= f.label :Image_url %>
    <%= f.text_field :Image_url %>
  </div>

  <div class="field">
    <%= f.label :Role %>
    <%= f.text_field :Role %>
  </div>

  <div class="field">
    <%= f.label :Location %>
    <%= f.text_field :Location %>
  </div>

  <div class="field">
    <%= f.label :Email %>
    <%= f.text_field :Email %>
  </div>

  <div class="field">
    <%= f.label :Phone %>
    <%= f.text_field :Phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

blog/app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resumes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th>Role</th>
      <th>Location</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.Name %></td>
        <td><%= resume.Image_url %></td>
        <td><%= resume.Role %></td>
        <td><%= resume.Location %></td>
        <td><%= resume.Email %></td>
        <td><%= resume.Phone %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

blog/app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', resumes_path %>

blog/app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resume.Name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @resume.Image_url %>
</p>

<p>
  <strong>Role:</strong>
  <%= @resume.Role %>
</p>

<p>
  <strong>Location:</strong>
  <%= @resume.Location %>
</p>

<p>
  <strong>Email:</strong>
  <%= @resume.Email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @resume.Phone %>
</p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>